version: '3'
services:
  db:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: studentsdb
    command: [ "postgres", "-c", "wal_level=logical" ]
    volumes:
      - studentsdb_data:/var/lib/postgresql/data

  app-custom:
    image: app-custom
    container_name: app-custom
    build:
      context: ./
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: host.docker.internal
    depends_on:
      - db

volumes:
  studentsdb_data: